[package]
name = "Dinvoke-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindings = { path = "bindings" }
windows = "0.19"
libc = "0.2.101"
winproc = "0.6.4"
winapi = "0.3"